### PR TITLE
Adapt to https://github.com/coq/coq/pull/15754

### PR DESCRIPTION
**Pull request by proux01**
This seems to be enough to get fiat-parser go through

### CODE REVIEW

**Comment by proux01** [comment]
@JasonGross there is no CI here, but that looks like the right fix to go forward with https://github.com/coq/coq/pull/15754

**Review by JasonGross — CHANGES_REQUESTED** [review]
These files are autogenerated by `generate-compat-files.sh`.  Please instead copy `compatibility/fragments/Grab88v814.v` to `compatibility/fragments/Grab88v816.v`, change the relevant lines in that file, and then change
https://github.com/JasonGross/coq-scripts/blob/3be05c7888f95f106ab4a637b3e354fd2cf3a783/compatibility/generate-compat-files.sh#L36
to
```bash
GRAB_88v814_VERSIONS="8_14 8_15"
GRAB_88v816_VERSIONS="8_16 master" 
```
and add
```bash
append "fragments/Grab88v816.v" "$GRAB_88v816_VERSIONS"
```
https://github.com/JasonGross/coq-scripts/blob/3be05c7888f95f106ab4a637b3e354fd2cf3a783/compatibility/generate-compat-files.sh#L43
and then rerun `generate-compat-files.sh`.

I can also try to find time to do this.

**Comment by proux01** [comment]
@JasonGross done, I also fixed my previous #7 that was not done properly (the change from `Numeral Notation` to `Number Notation` happened in 8.13, so we don't need a `Grab88v815.v` specifi file).

**Review by JasonGross — APPROVED** [review]
Thanks!

**Pull request merged**
